services:
  trading-platform:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_AUTH_API_URL=http://localhost:5168
      - NEXT_PUBLIC_TRADING_API_URL=http://localhost:5193
      - NEXT_PUBLIC_WS_URL=ws://localhost:5194
    restart: unless-stopped
    networks:
      - trading-network

networks:
  trading-network:
    driver: bridge